name: Java CI with Maven # Имя рабочего процесса

on:
  push:
    branches: [ "main" ] # Запуск при пуше в ветку main
  pull_request:
    branches: [ "main" ] # Запуск при Pull Request в main

jobs:
  build:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu

    steps:
    - uses: actions/checkout@v4 # Шаг 1: Клонируем репозиторий

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11' # Указываем версию Java 11
        distribution: 'temurin'
        cache: maven # Кэшируем зависимости Maven

    - name: Build and Verify with Maven
      # Запускаем команду, которая выполняет тесты и проверку JaCoCo
      run: mvn clean verify
